USE [QL_DH_GH_ONLINE]
GO
/*NON-REPEATABLE READ*/
/*T2*/
CREATE OR ALTER PROCEDURE TX_CAPNHAT_TTGH @MATX CHAR(5), @MADH CHAR(5), @TTGH NVARCHAR(40)
AS
BEGIN TRAN
	UPDATE DONGIAOHANG
	SET TTGIAOHANG = @TTGH
	WHERE MADH = @MADH AND MATX = @MATX
COMMIT TRAN
GO
EXEC TX_CAPNHAT_TTGH 'TX001','DH001', N'Đang vận chuyển'


