USE [QL_DH_GH_ONLINE]
GO
/*CYCLE DEADLOCK*/
/* T1 */
CREATE PROCEDURE QL1_DEADLOCK @USERID CHAR(5), @PASS_NEW CHAR(10), @MATX CHAR(5), @CMND_NEW CHAR(10)
AS
BEGIN TRAN
	UPDATE LOGIN SET PASSWORD = @PASS_NEW WHERE USERID = @USERID
	WAITFOR DELAY '00:00:05'

	UPDATE TAIXE
	SET CMND = @CMND_NEW
	WHERE MATX = @MATX
COMMIT TRAN
GO
/*Delete account admin*/
DELETE LOGIN WHERE USERID = 'admin'
GO
/*Insert admin1 to demo*/
EXEC SP_INSERT_LOGIN 'QT001', 'admin1', 'admin1', N'Quản trị'
GO
/*Demo deadlock*/
EXEC QL1_DEADLOCK 'KH001', '123', 'TX001', '2132123339'
