USE [QL_DH_GH_ONLINE]
GO
/*CYCLE DEADLOCK*/
/* T2 */
CREATE PROCEDURE QL2_DEADLOCK @USERID CHAR(5), @PASS_NEW CHAR(10), @MATX CHAR(5), @CMND_NEW CHAR(10)
AS
BEGIN TRAN
	UPDATE TAIXE
	SET CMND = @CMND_NEW
	WHERE MATX = @MATX
	WAITFOR DELAY '00:00:05'

	UPDATE LOGIN SET PASSWORD = @PASS_NEW WHERE USERID = @USERID
COMMIT TRAN
GO
/*Insert admin 2 */
EXEC SP_INSERT_LOGIN 'QT002', 'admin2', 'admin2', N'Quản trị'
/*Demo deadlock*/
EXEC QL2_DEADLOCK 'KH001', '123', 'TX001', '2132123339'