USE [QL_DH_GH_ONLINE]
GO
/* DIRTY READ */
/* T2 */
CREATE OR ALTER PROCEDURE KH_XEMGIA_SP @MASP CHAR(5)
AS
BEGIN TRAN
     SELECT *
     FROM SANPHAM WITH(NOLOCK)
	 WHERE MASP = @MASP
COMMIT TRAN
GO
EXEC KH_XEMGIA_SP 'SP006'